# autogenerated by txs
\begin{blockm}#S
\begin{blocks}#S
\begin{mlaquotation}#S
\begin{mlaquote}#S
\begin{workscited}#S
\bibent#S
\end{blockm}#S
\end{blocks}#S
\end{mlaquotation}#S
\end{mlaquote}#S
\end{workscited}#S
\lastname#S
\tab#S
