# autogenerated by txs
\WFclear#S
\endwrapfloat#S
\expandafter#S
\noexpand#S
\width#S
\wrapfigure#S
\wrapfloat{arg1}#S
\wraptable#S
\\newfloatlist#S
\begin{wrapfigure}
\begin{wrapfloat}
\begin{wraptable}
\end{wrapfigure}
\end{wrapfloat}
\end{wraptable}
\newfloat#S
