# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1492375139);
user_pref("app.update.lastUpdateTime.background-update-timer", 1492375139);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1492375139);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1492375139);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 768000);
user_pref("dom.disable_window_open_feature.status", false);
user_pref("idle.lastDailyNotification", 1492375728);
user_pref("intl.accept_languages", "en-us,en");
user_pref("intl.charset.default", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1492375728);
user_pref("places.history.expiration.transient_current_max_pages", 100818);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1492375728);
