# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html
import gruvbox

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
c.fonts.monospace = 'Roboto Mono for Powerline'

# How to behave when the last tab is closed.
# Type: String
# Valid values:
#   - ignore: Don't do anything.
#   - blank: Load a blank page.
#   - startpage: Load the start page.
#   - default-page: Load the default page.
#   - close: Close the window.
c.tabs.last_close = 'close'

# When to show the tab bar.
# Type: String
# Valid values:
#   - always: Always show the tab bar.
#   - never: Always hide the tab bar.
#   - multiple: Hide the tab bar if only one tab is open.
#   - switching: Show the tab bar when switching tabs.
c.tabs.show = 'multiple'

# Open a new window for every tab.
# Type: Bool
c.tabs.tabs_are_windows = True

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# Type: FuzzyUrl
c.url.default_page = 'file://~/startpage/'

# Search engines which can be used via the address bar. Maps a search
# engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
# placeholder. The placeholder will be replaced by the search term, use
# `{{` and `}}` for literal `{`/`}` signs. The search engine named
# `DEFAULT` is used when `url.auto_search` is turned on and something
# else than a URL was entered to be opened. Other search engines can be
# used by prepending the search engine name to the search term, e.g.
# `:open google qutebrowser`.
# Type: Dict
c.url.searchengines = {'DEFAULT': 'https://google.com/search?q={}'}

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = 'file://~/startpage/'

c.colors.completion.category.bg = gruvbox.bg0_h
c.colors.completion.category.border.bottom = gruvbox.bg0_h
c.colors.completion.category.border.top = gruvbox.bg0_h
c.colors.completion.category.fg = gruvbox.fg
c.colors.completion.even.bg = gruvbox.bg1
c.colors.completion.odd.bg = gruvbox.bg2
c.colors.completion.fg = gruvbox.fg
c.colors.completion.item.selected.bg = gruvbox.green_l
c.colors.completion.item.selected.border.bottom = gruvbox.green_l
c.colors.completion.item.selected.border.top = gruvbox.green_l
c.colors.completion.item.selected.fg = gruvbox.bg
c.colors.completion.match.fg = gruvbox.red
c.colors.completion.scrollbar.bg = gruvbox.bg1
c.colors.completion.scrollbar.fg = gruvbox.fg
c.colors.downloads.bar.bg = gruvbox.bg
c.colors.downloads.error.bg = gruvbox.red
c.colors.downloads.error.fg = gruvbox.bg
c.colors.downloads.start.bg = gruvbox.blue
c.colors.downloads.start.fg = gruvbox.bg
c.colors.downloads.stop.bg = gruvbox.green
c.colors.downloads.stop.fg = gruvbox.bg
c.colors.hints.bg = gruvbox.purple
c.colors.hints.fg = gruvbox.bg
c.colors.hints.match.fg = gruvbox.red
c.colors.keyhint.bg = gruvbox.bg
c.colors.keyhint.fg = gruvbox.fg
c.colors.keyhint.suffix.fg = gruvbox.red
c.colors.messages.error.bg = gruvbox.red
c.colors.messages.error.border = gruvbox.red
c.colors.messages.error.fg = gruvbox.bg
c.colors.messages.info.bg = gruvbox.bg
c.colors.messages.info.border = gruvbox.bg
c.colors.messages.info.fg = gruvbox.fg
c.colors.messages.warning.bg = gruvbox.yellow
c.colors.messages.warning.border = gruvbox.yellow
c.colors.messages.warning.fg = gruvbox.bg
c.colors.statusbar.caret.bg = gruvbox.blue
c.colors.statusbar.caret.fg = gruvbox.bg
c.colors.statusbar.caret.selection.bg = gruvbox.bg
c.colors.statusbar.caret.selection.fg = gruvbox.blue

c.colors.statusbar.command.bg = gruvbox.bg
c.colors.statusbar.command.fg = gruvbox.fg

c.colors.statusbar.command.private.bg = gruvbox.purple
c.colors.statusbar.command.private.fg = gruvbox.bg

c.colors.statusbar.insert.bg = gruvbox.green
c.colors.statusbar.insert.fg = gruvbox.bg

c.colors.statusbar.normal.bg = gruvbox.bg
c.colors.statusbar.normal.fg = gruvbox.fg

c.colors.statusbar.passthrough.fg = gruvbox.green_l
c.colors.statusbar.passthrough.fg = gruvbox.bg

c.colors.statusbar.private.bg = gruvbox.purple
c.colors.statusbar.private.fg = gruvbox.bg

c.colors.statusbar.progress.bg = gruvbox.fg

c.colors.statusbar.url.error.fg = gruvbox.red
c.colors.statusbar.url.fg = gruvbox.fg
c.colors.statusbar.url.hover.fg = gruvbox.aqua
c.colors.statusbar.url.success.http.fg = gruvbox.fg
c.colors.statusbar.url.success.https.fg = gruvbox.fg
c.colors.statusbar.url.warn.fg = gruvbox.yellow

