# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#151a1f'
foreground='b5b7bb'
cursor='#c69f98'

# Colors
color0='#151a1f'
color1='#4a5a6c'
color2='#998c90'
color3='#c69f98'
color4='#606352'
color5='#b2c5cf'
color6='#dc9570'
color7='#b5b7bb'
color8='#7e8082'
color9='#4a5a6c'
color10='#998c90'
color11='#c69f98'
color12='#606352'
color13='#b2c5cf'
color14='#dc9570'
color15='#b5b7bb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
